---
language: php
matrix:
  include:
    - php: 8.0
    - php: 7.4
    - php: 7.3
    - php: 7.2

install:
  - composer install

script:
  - vendor/bin/phpstan analyse -c phpstan.neon
  - vendor/bin/atoum
